/**
 * Basic Annex IV Report Generation
 *
 * Generates a complete ESMA-compliant Annex IV XML report for a
 * German real estate Spezial-AIF. Run with:
 *
 *   npx ts-node examples/basic-report.ts
 *
 * Or after building:
 *
 *   node examples/basic-report.js
 */

import {
  serializeAnnexIVToXml,
  type AnnexIVReport,
} from '../src/index.js';

const report: AnnexIVReport = {
  aif_identification: {
    reporting_period: { start: '2025-01-01', end: '2025-03-31' },
    aif_name: 'Muster Immobilien Spezial-AIF',
    aif_national_code: 'DE000001',
    aif_type: 'Spezial_AIF',
    domicile: 'Germany',
    inception_date: '2020-01-15',
    aifm_name: 'Muster KVG GmbH',
    aifm_lei: '529900EXAMPLE000LEI00',
    reporting_obligation: 'Article 24(2)',
    base_currency: 'EUR',
  },

  investor_concentration: {
    total_investors: 12,
    by_type: [
      { investor_type: 'professional', count: 8, percentage_of_nav: 72.5 },
      { investor_type: 'retail', count: 4, percentage_of_nav: 27.5 },
    ],
    by_domicile: [
      { domicile: 'Germany', count: 10, percentage_of_nav: 85.0 },
      { domicile: 'Austria', count: 2, percentage_of_nav: 15.0 },
    ],
    beneficial_owners_concentration: {
      top_5_investors_pct: 45.2,
    },
  },

  principal_exposures: {
    total_aum_units: 10000,
    total_allocated_units: 8500,
    total_aum_eur: 150_000_000,
    total_nav_eur: 127_500_000,
    utilization_pct: 85.0,
    asset_breakdown: [
      {
        asset_name: 'Berlin Office Portfolio',
        asset_type: 'real_estate',
        units: 5000,
        value_eur: 75_000_000,
        percentage_of_total: 58.8,
      },
      {
        asset_name: 'Munich Residential Fund',
        asset_type: 'real_estate',
        units: 3000,
        value_eur: 52_500_000,
        percentage_of_total: 41.2,
      },
    ],
  },

  depositary: {
    name: 'CACEIS Bank S.A., Germany Branch',
    lei: '96950023O5B6JXLY0S86',
    jurisdiction: 'Germany',
    type: 'credit_institution',
  },

  sub_asset_type: 'PHY_RES_RESD',

  leverage: {
    commitment_method: 1.2,
    gross_method: 1.4,
    commitment_limit: 2.0,
    gross_limit: 3.0,
    leverage_compliant: true,
  },

  risk_profile: {
    liquidity: {
      investor_redemption_frequency: 'Quarterly',
      portfolio_liquidity_profile: [
        { bucket: '31-90d', pct: 15.0 },
        { bucket: '91-180d', pct: 25.0 },
        { bucket: '181-365d', pct: 30.0 },
        { bucket: '>365d', pct: 30.0 },
      ],
      liquidity_management_tools: [
        {
          type: 'notice_period',
          description: '90-day redemption notice period',
          threshold_pct: 100,
          active: true,
        },
        {
          type: 'redemption_gate',
          description: 'Quarterly redemption gate at 10% NAV',
          threshold_pct: 10,
          active: true,
        },
      ],
    },
    operational: {
      total_open_risk_flags: 1,
      high_severity_flags: 0,
    },
  },

  geographic_focus: [
    { region: 'Germany', pct: 85.0 },
    { region: 'Austria', pct: 15.0 },
  ],

  counterparty_risk: {
    top_5_counterparties: [
      { name: 'Deutsche Bank AG', lei: '7LTWFZYICNSX8D621K86', exposure_pct: 12.5 },
      { name: 'Commerzbank AG', lei: '851WYGNLUQLFZBSBER57', exposure_pct: 8.3 },
    ],
    total_counterparty_count: 7,
  },

  compliance_status: {
    kyc_coverage_pct: 100,
    eligible_investor_pct: 100,
    recent_violations: 0,
    last_compliance_check: '2025-03-31T00:00:00Z',
  },

  generated_at: new Date().toISOString(),
  report_version: '1.0',
  disclaimer: 'Generated by open-annex-iv. For regulatory reporting purposes only.',
};

// Generate XML
const xml = serializeAnnexIVToXml(report);
console.log(xml);

// To save to file:
// import { writeFileSync } from 'node:fs';
// writeFileSync('annex-iv-report.xml', xml, 'utf-8');
// console.log('Written to annex-iv-report.xml');
